sudo: false
language: python
dist: xenial
python:
  - "3.6"
services:
  - docker
addons:
  postgresql: "9.4"
script:
  - docker exec -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID"
                -e TRAVIS_BRANCH="$TRAVIS_BRANCH"
                -e DATABASE_DB_NAME="travis_ci_test"
                -e DATABASE_USERNAME="travis"
                -e DATABASE_HOST="localhost"
