sudo: false
language: minimal
dist: xenial
matrix:
  include:
    - language: python
      python: 3.6
      cache: pip
      addons:
        apt:
          update: true
          packages:
            - libxmlsec1-dev
        postgresql: "9.4"
      install:
        - pip install coverage
        - pip install python-coveralls
        - pip install pycodestyle
        - pip install . 
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - cp travis/manage.py manage.py
        - python manage.py migrate --noinput
      script:
        - pycodestyle foodalert/ --exclude=migrations
        - coverage run --source=foodalert/ --omit=foodalert/migrations/* manage.py test foodalert
      after_script:
        - coveralls
    - language: node_js
      node_js: 8.15.1
      cache: npm
      install:
        - npm install eslint eslint-config-google eslint-plugin-vue eslint-plugin-vue-a11y
      script:
        - ./node_modules/.bin/eslint --ext .js,.vue foodalert/static/foodalert/js/
        - npx webpack
    - language: minimal
      services:
        - docker
      script:
        - docker-compose -f docker-compose.test.yml build
        - docker-compose -f docker-compose.test.yml run taster
