sudo: required

language: python
python:
  - 3.6

services:
  - docker

os:
  - linux

env:
  global:
    - RELEASE_NAME="uw-foodalert"
    - DJANGO_APP="foodalert"
    - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
    - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"

install:
  - docker build -t "$IMAGE_TAG" .

before_script:
  - pip install coverage
  - pip install coveralls

script:
  - docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev" "$IMAGE_TAG" bash -c ". ./travis/test.sh"

after_success:
  - cp /tmp/.coverage* .
  - coverage combine
  - coveralls
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" =~ ^(develop|master)$ ]]; then
    curl -Ls ${DEPLOY_SCRIPT_BASE}/travis-ci/deploy.sh | bash;
    fi

cache:
  directories:
    - "$HOME/helm"
    - "$HOME/kubeval"