sudo: false
dist: xenial
services:
  - docker
addons:
  postgresql: "9.4"
script:
  - docker build --build-arg BUILD_STAGE=test -t foodalert .
  - CONTAINER=$(docker create foodalert)
  - docker cp  "$container:/app/js-coverage.json" "."
  - docker cp  "$container:/app/.coverage" "."
  - coveralls --merge=js-coverage.json
