sudo: false
language: minimal
dist: xenial
addons:
  apt:
    update: true
    packages:
      - libxmlsec1-dev
  chrome: stable
  postgresql: "9.4"
matrix:
  include:
    - language: python
      python: 3.6
      cache: pip
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - pip install coverage
        - pip install python-coveralls
        - pip install pycodestyle
        - pip install .
        - cp travis/manage.py manage.py
        - python manage.py migrate --noinput
      script:
        - npx webpack
        - pycodestyle foodalert/ --exclude=migrations
        - coverage run --source=foodalert/ --omit=foodalert/migrations/* manage.py test foodalert
    - language: node_js
      node_js: 8.15.1
      cache: npm
      before_script:
        - npm install
      script:
        - ./node_modules/.bin/eslint --ext .js,.vue foodalert/static/foodalert/js/components/
        - ./node_modules/.bin/eslint --ext .js,.vue foodalert/static/foodalert/js/pages/
        - ./node_modules/.bin/eslint --ext .js,.vue foodalert/static/foodalert/js/*.js
after_script:
  - coveralls
