sudo: false
language: python
python:
  - "3.6"
install:
  - apt-get update && apt-get install -y libxmlsec1-dev
  - python setup.py -q install
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pycodestyle
  - pip install .
  - cp sampleproj/manage.py manage.py
  - python manage.py migrate --noinput
  - npm install
  - npm list
  - gem install coveralls-lcov
script:
  - npx webpack
  - pycodestyle foodalert/ --exclude=migrations
  - npx jest --coverage && coveralls-lcov -v -n ./coverage/lcov.info > js-coverage.json
  - coverage run --source=foodalert/ --omit=foodalert/migrations/* manage.py test foodalert --settings=sampleproj.settings.travis
after_script:
  - coveralls --merge=js-coverage.json

