sudo: false
language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - python setup.py -q install
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pycodestyle
  - pip install .
  - cp sampleproj/manage.py manage.py
  - python manage.py migrate --noinput
  - npm install
  - npm list
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npx webpack
  - pycodestyle foodalert/ --exclude=migrations
  - coverage run --source=foodalert/ --omit=foodalert/migrations/* manage.py test foodalert --settings=sampleproj.settings.travis
after_script:
  - coveralls

