sudo: false
language: minimal
dist: xenial
addons:
  apt:
    update: true
    packages:
      - libxmlsec1-dev
  chrome: stable
  postgresql: "9.4"
matrix:
  include:
    - language: python
      python: 3.6
      cache: pip
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
        - pip install coverage
        - pip install python-coveralls
        - pip install pycodestyle
        - pip install .
        - cp travis/manage.py manage.py
        - python manage.py migrate --noinput
      script:
        - pycodestyle foodalert/ --exclude=migrations
        - coverage run --source=foodalert/ --omit=foodalert/migrations/* manage.py test foodalert
    - language: node_js
      node_js: 8.15.1
      cache: npm
      before_script:
        - npm install
      script:
        - ./node_modules/.bin/eslint --ext .js,.vue foodalert/static/foodalert/js/
        - npx webpack
    - language: node_js
      node_js: 12.9.1
      services:
        - docker
      install: true
      script:
        - docker-compose -f docker-compose.test.yml build
        - docker-compose -f docker-compose.test.yml up -d
        - rm package.json package-lock.json
        - npm install nightwatch chromedriver
        - ./node_modules/.bin/nightwatch
after_script:
  - coveralls
