version: '3'

services:
  app:
    restart: always
    build: .
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      # - ./sampleproj:/app/sampleproj/
      - ./foodalert:/app/foodalert
      # - ./docs:/app/docs/
    links:
      - db
    environment:
      AUTH: SAML_MOCK
    ports:
      - "${APACHE_PORT:-8080}:80"
      - "${RUNSERVER_PORT:-8000}:8000"
    #command: bash -c "bin/python manage.py migrate && bin/python manage.py runserver 0:8000"
  db:
    image: postgres
