version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: BaseContainer
    volumes:
      - ./foodalert:/app/foodalert
      - ./docker/settings.py:/app/project/settings.py
      - ./docker/urls.py:/app/project/urls.py
      - shared-static:/app/foodalert/static
    links:
      - db
    environment:
      AUTH: SAML_MOCK
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    command: bash -c "bin/python manage.py migrate && bin/python manage.py runserver 0:8000"
  db:
    image: postgres
  devtools:
    container_name: devtools
    image: node:8.15.1-jessie
    volumes:
      - ./package.json:/home/node/package.json
      - ./package-lock.json:/home/node/package-lock.json
      - shared-static:/devtools/uw-foodalert/foodalert/static
    command: bash -c "yes yes | npm install; npx webpack --watch"
volumes:
  shared-static:
