version: '3'

services:
  app:
    restart: always
    build:
      context: .
    volumes:
      - ./foodalert:/app/foodalert
      - ./docker/settings.py:/app/project/settings.py
      - ./docker/urls.py:/app/project/urls.py
    links:
      - db
    environment:
      AUTH: SAML_MOCK
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    command: bash -c "bin/python manage.py migrate && bin/python manage.py runserver 0:8000"
  db:
    image: postgres
  devtools:
    container_name: foodalert-devtools
    image: node:8.15.1-jessie
    working_dir: /devtools/uw-foodalert
    volumes:
      - ./package.json:/devtools/uw-foodalert/package.json
      - ./webpack.config.js:/devtools/uw-foodalert/webpack.config.js
      - ./foodalert:/devtools/uw-foodalert/foodalert
    command: bash -c "yes yes | npm install; npx webpack --watch"
