version: '3'

services:
  food:
    restart: always
    build: .
    links:
      - db
    environment:
      DATABASE_DB_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
      DB: ${DB:-sqlite3}
      AUTH: ${AUTH:-SAML_MOCK}
  db:
    image: postgres
  taster:
    build:
      context: ./nightwatch
    depends_on:
      - food
    volumes:
      - ./nightwatch/tests:/home/node/tests
      - ./nightwatch/vrt:/home/node/vrt
    privileged: true
    command: ./wait-for-it.sh food:8000 -- ./node_modules/.bin/nightwatch
