version: '3'

services:
  app:
    restart: always
    build: .
    volumes:
      - ./foodalert:/app/foodalert
      - ./docker/settings.py:/app/project/settings.py
      - ./docker/urls.py:/app/project/urls.py
    links:
      - db
    environment:
      DATABASE_DB_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
      DB: ${DB:-sqlite3}
      AUTH: ${AUTH:-SAML_MOCK}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-NONE}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-NONE}
      TWILIO_NOTIFY_SERVICE_ID: ${TWILIO_NOTIFY_SERVICE_ID:-NONE}
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  db:
    image: postgres
  devtools:
    container_name: foodalert-devtools
    image: node:8.15.1-jessie
    working_dir: /devtools/uw-foodalert
    environment:
      ENV: localdev
    volumes:
      - ./package.json:/devtools/uw-foodalert/package.json
      - ./webpack.config.js:/devtools/uw-foodalert/webpack.config.js
      - ./foodalert:/devtools/uw-foodalert/foodalert
    command: bash -c "yes yes | npm install; npx webpack --watch"
