version: '3'

services:
  app:
    restart: always
    build: .
    volumes:
      - ./foodalert:/app/foodalert
      - ./docker/settings.py:/app/project/settings.py
      - ./docker/urls.py:/app/project/urls.py
    depends_on:
      - db
    environment:
      AUTH: ${AUTH:-SAML_MOCK}
      DJANGO_LOGIN_USERNAME: ${DJANGO_LOGIN_USERNAME:-javerage}
      DJANGO_LOGIN_PASSWORD: ${DJANGO_LOGIN_PASSWORD:-javerage}
      DJANGO_LOGIN_EMAIL: ${DJANGO_LOGIN_EMAIL:-javerage@uw.edu}
      DATABASE_DB_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME:-db}
      DATABASE_HOST: db
      DB: ${DB:-postgres}
      EMAIL_HOST: ${EMAIL_HOST:-NONE}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL:-NONE}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD:-NONE}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER:-NONE}
      GOOGLE_ANALYTICS_KEY: ${GOOGLE_ANALYTICS_KEY}
      SAFE_EMAIL_RECIPIENT: ${SAFE_EMAIL_RECIPIENT:-NONE}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-NONE}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-NONE}
      TWILIO_NOTIFY_SERVICE_ID: ${TWILIO_NOTIFY_SERVICE_ID:-NONE}
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  devtools:
    container_name: foodalert-devtools
    image: node:8.15.1-jessie
    working_dir: /devtools/uw-foodalert
    environment:
      ENV: localdev
    volumes:
      - ./package.json:/devtools/uw-foodalert/package.json
      - ./webpack.config.js:/devtools/uw-foodalert/webpack.config.js
      - ./foodalert:/devtools/uw-foodalert/foodalert
    command: bash -c "yes yes | npm install; npx webpack --watch"
