version: '3'

services:
  app:
    restart: always
    build: .
    links:
      - db
    environment:
      AUTH: SAML_MOCK
      ENV: ENV
    ports:
      - "${APACHE_PORT:-8080}:80"
  db:
    image: postgres
