version: '3'

services:
  app:
    restart: always
    build: .
    links:
      - db
    environment:
      AUTH: SAML_MOCK
      ENV: ENV
      DJANGO_SECRET: DJANGO_SECRET
    ports:
      - "${APACHE_PORT:-8000}:8000"
  db:
    image: postgres
