version: '3'

services:
  app:
    restart: always
    build: .
    volumes:
      - ./foodalert:/app/foodalert
    links:
      - db
    environment:
      AUTH: SAML_MOCK
    ports:
      - "${APACHE_PORT:-8000}:80"
  db:
    image: postgres
