version: '3'

services:
  app:
    restart: always
    build: .
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./sampleproj:/app/sampleproj/
      - ./foodalert:/app/foodalert
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    command: bash -c "python manage.py migrate --settings=sampleproj.settings.local && python manage.py runserver 0.0.0.0:${PORT:-8000} --settings=sampleproj.settings.local"

