version: '3'

services:
  app:
    restart: always
    build: .
    volumes:
      - ./foodalert:/app/foodalert
    links:
      - db
    environment:
      AUTH: SAML_MOCK
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    command: bash -c "bin/python manage.py migrate && bin/python manage.py runserver 0:8000"
  db:
    image: postgres
