version: '3'

services:
  food:
    restart: always
    build: .
    links:
      - db
    environment:
      DATABASE_DB_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
      DB: ${DB:-sqlite3}
      AUTH: ${AUTH:-SAML_MOCK}
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
  db:
    image: postgres
