# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
                ('location_details', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.CharField(max_length=40)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('food_served', models.CharField(max_length=100)),
                ('amount_of_food_left', models.CharField(max_length=100)),
                ('bring_container', models.BooleanField(default=False)),
                ('host_permit_number', models.CharField(blank=True, max_length=40, null=True)),
                ('host_user_agent', models.CharField(max_length=40)),
                ('allergens', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='foodalert.Allergen')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('notification', models.ManyToManyField(to='foodalert.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('parent_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodalert.Notification')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='safe_foods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safe_foods', to='foodalert.SafeFood'),
        ),
        migrations.AddField(
            model_name='allergen',
            name='notification',
            field=models.ManyToManyField(to='foodalert.Notification'),
        ),
    ]
