# Generated by Django 2.1 on 2019-08-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0002_subscription_notif_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='safe_foods',
        ),
        migrations.AddField(
            model_name='subscription',
            name='email_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='SafeFood',
        ),
    ]
