# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='host_user_agent',
            field=models.CharField(max_length=80),
        ),
    ]
