# Generated by Django 2.1 on 2019-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0002_subscription_notif_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='notif_on',
            new_name='send_email',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='safe_foods',
        ),
        migrations.AddField(
            model_name='subscription',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='SafeFood',
        ),
    ]
