# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0003_auto_20181102_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='allergens',
        ),
        migrations.AddField(
            model_name='notification',
            name='allergens',
            field=models.ManyToManyField(blank=True, null=True, related_name='allergens', to='foodalert.Allergen'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='safe_foods',
        ),
        migrations.AddField(
            model_name='notification',
            name='safe_foods',
            field=models.ManyToManyField(blank=True, null=True, related_name='safe_foods', to='foodalert.SafeFood'),
        ),
    ]
