# Generated by Django 2.1.11 on 2019-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0003_auto_20190827_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalName', models.CharField(max_length=20, unique=True)),
                ('externalName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='food_qualification',
        ),
        migrations.AddField(
            model_name='notification',
            name='food_qualifications',
            field=models.ManyToManyField(to='foodalert.FoodQualification'),
        ),
    ]
