# Generated by Django 2.1.12 on 2019-09-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0004_auto_20190904_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='amount_of_food_left',
        ),
    ]
