# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0004_auto_20181106_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='safefood',
            name='notification',
        ),
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='allergens', to='foodalert.Allergen'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='safe_foods',
            field=models.ManyToManyField(blank=True, related_name='safe_foods', to='foodalert.SafeFood'),
        ),
        migrations.AlterField(
            model_name='safefood',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
