# Generated by Django 2.2.8 on 2019-12-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0005_remove_notification_amount_of_food_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='food_served',
            field=models.CharField(max_length=200),
        ),
    ]
