# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0005_auto_20181106_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='safefood',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
