# Generated by Django 2.2.9 on 2020-01-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0006_auto_20191206_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='twilio_stop',
            field=models.BooleanField(default=False),
        ),
    ]
