# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0006_auto_20181106_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
