# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0007_update_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='timestamp',
            new_name='created_time',
        ),
    ]
