# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0008_auto_20190104_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='host_user_agent',
            field=models.CharField(max_length=256),
        ),
    ]
