# Generated by Django 2.2.11 on 2020-03-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0008_subscription_twilio_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='update',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
