# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodalert', '0010_auto_20190111_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='location_details',
        ),
        migrations.AlterField(
            model_name='notification',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
