ingress:
  enabled: true
  tls:
    foodalert:
      secretName: foodalert.aca-aws.s.uw.edu
      hosts:
        - foodalert.aca-aws.s.uw.edu
  hosts:
    foodalert:
      host: foodalert.aca-aws.s.uw.edu
      paths: 
        - "/"
database:
  secretName: foodalert-eval-rds
  hostname: foodalert-eval-rds.default.svc.cluster.local
  name: foodalert
repo: foodalert-map
branch: develop
environmentVariables:
  - name: SWS_ENV
    value: PROD
