ingress:
  enabled: true
  tls:
    foodalert:
      secretName: foodalert.aca-aws.s.uw.edu
      hosts:
        - foodalert.aca-aws.s.uw.edu
  hosts:
    foodalert:
      host: foodalert.aca-aws.s.uw.edu
      paths: 
        - "/"
database:
  secretName: foodalert-eval-rds
  hostname: foodalert-eval-rds.default.svc.cluster.local
  name: foodalert
  engine: postgres
repo: foodalert-map
branch: aws
environmentVariables:
  - name: AUTH
    value: SAML
  - name: IDP_CERT
    value: MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM=
  - name: CLUSTER_CNAME
    value: foodalert.aca-aws.s.uw.edu
  - name: SAML_ENTITY_ID
    value: https://foodalert.aca-aws.s.uw.edu
  - name: SESSION_EXPIRE_AT_BROWSER_CLOSE
    value: "TRUE"
  - name: FA_HOST_GROUP
    value: u_acadev_foodalert-eval-hosts
  - name: FA_AUDIT_GROUP
    value: u_acadev_foodalert-eval-auditors
environmentVariablesSecrets:
  twilioSID:
    name: TWILIO_ACCOUNT_SID
    secretName: foodalert-eval-twillio
    secretKey: sid
  twilioSecret:
    name: TWILIO_AUTH_TOKEN
    secretName: foodalert-eval-twillio
    secretKey: secret
  twilioNSID:
    name: TWILIO_NOTIFY_SERVICE_ID
    secretName: foodalert-eval-twillio
    secretKey: service_sid
  emailSafeEmail:
    name: SAFE_EMAIL_RECIPIENT
    secretName: foodalert-eval-email
    secretKey: safe_email
  emailEmailHost:
    name: EMAIL_HOST
    secretName: foodalert-eval-email
    secretKey: email_host
  emailEmailHostUser:
    name: EMAIL_HOST_USER
    secretName: foodalert-eval-email
    secretKey: email_host_user
  emailEmailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: foodalert-eval-email
    secretKey: email_host_password
  emailDefaultFromEmail:
    name: DEFAULT_FROM_EMAIL
    secretName: foodalert-eval-email
    secretKey: default_from_email
  spCert:
    name: SP_CERT
    secretName: foodalert.aca-aws.s.uw.edu
    secretKey: tls.crt
  djangoSecret:
    name: DJANGO_SECRET
    secretName: foodalert-eval-django-secret
    secretKey: secret
  googleSecret:
    name: GOOGLE_ANALYTICS_KEY
    secretName: foodalert-eval-google-secret
    secretKey: secret

