version: '3'

services:
  food:
    restart: always
    build: ../
    links:
      - db
    environment:
      DATABASE_DB_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
      DB: ${DB:-sqlite3}
      AUTH: ${AUTH:-SAML_MOCK}
  db:
    image: postgres
  cypress:
    build:
      context: .
      args:
        curr_uid: ${USERID:-1000}
        curr_gid: ${GROUPID:-1000}
    depends_on:
      - food
    volumes:
      - ./cypress:/home/node/e2e/cypress
      - ./cypress.json:/home/node/e2e/cypress.json
      - ./docker-compose.yml:/home/node/e2e/docker-compose.yml
      - ./package-lock.json:/home/node/e2e/package-lock.json
      - ./package.json:/home/node/e2e/package.json
    working_dir: /home/node/e2e
    command: ./node_modules/.bin/cypress run --browser chrome --env updateSnapshots=$UPDATE_SNAPSHOTS
