version: '3'

services:
  food:
    restart: always
    build: ../
    links:
      - db
    environment:
      DATABASE_DB_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
      DB: ${DB:-sqlite3}
      AUTH: ${AUTH:-SAML_MOCK}
  db:
    image: postgres
  taster:
    image: cypress/included:3.4.1
    command: ["--browser", "chrome"]
    depends_on:
      - food
    volumes:
      - .:/e2e
    working_dir: /e2e
